name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Inject API Key
      run: echo "API_KEY=${{ secrets.API_KEY }}" > .env

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        # Aqui você adiciona os comandos para o seu processo de deploy
        # Por exemplo, se você estiver usando GitHub Pages:
        npm run deploy